// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9IUKYC2GymkfQkb6QKFrK5XOGAS_7rI',
    appId: '1:762857605833:web:caae48d167ef130e495b18',
    messagingSenderId: '762857605833',
    projectId: 'flavorfi',
    authDomain: 'flavorfi.firebaseapp.com',
    storageBucket: 'flavorfi.firebasestorage.app',
    measurementId: 'G-YQ810N8KHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABih-4zATZCfaFQto_i-7aD3Wa2i1IkAs',
    appId: '1:762857605833:android:8a2e15ca65c8392e495b18',
    messagingSenderId: '762857605833',
    projectId: 'flavorfi',
    storageBucket: 'flavorfi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNQlLZo3K2ygkcJMXnbIGww-LjVzpwOOU',
    appId: '1:762857605833:ios:017413484ec09958495b18',
    messagingSenderId: '762857605833',
    projectId: 'flavorfi',
    storageBucket: 'flavorfi.firebasestorage.app',
    iosBundleId: 'com.example.flavorFi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNQlLZo3K2ygkcJMXnbIGww-LjVzpwOOU',
    appId: '1:762857605833:ios:017413484ec09958495b18',
    messagingSenderId: '762857605833',
    projectId: 'flavorfi',
    storageBucket: 'flavorfi.firebasestorage.app',
    iosBundleId: 'com.example.flavorFi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa9IUKYC2GymkfQkb6QKFrK5XOGAS_7rI',
    appId: '1:762857605833:web:0d873273999b6a0e495b18',
    messagingSenderId: '762857605833',
    projectId: 'flavorfi',
    authDomain: 'flavorfi.firebaseapp.com',
    storageBucket: 'flavorfi.firebasestorage.app',
    measurementId: 'G-W1YQZ58TKR',
  );
}
